test_that("validate_vacc_activities detects invalid object generated by popim_vacc_activities", {
    x <- popim_vacc_activities(region = "UK", year = 2000,
                             age_first = -1, age_last = 10,
                             coverage = 0.3, doses = NA, targeting = "random")
    expect_equal(nrow(x), 1)
    expect_error(validate_vacc_activities(x)) ## because age_first

    x <- popim_vacc_activities(region = "UK", year = 2000,
                             age_first = 10, age_last = 5,
                             coverage = 0.3, doses = NA, targeting = "random")
    expect_equal(nrow(x), 1)
    expect_error(validate_vacc_activities(x)) ## because age_last < age_first

    x <- popim_vacc_activities(region = "UK", year = 2000,
                             age_first = 0, age_last = 5,
                             coverage = 2, doses = NA, targeting = "random")
    expect_equal(nrow(x), 1)
    expect_error(validate_vacc_activities(x)) ## because coverage

    x <- popim_vacc_activities(region = "UK", year = 2000,
                             age_first = 0, age_last = 5,
                             coverage = 0.5, doses = NA, targeting = "blue")

    expect_equal(nrow(x), 1)
    expect_error(validate_vacc_activities(x)) ## because targeting
    
    
    
    x <- popim_vacc_activities(region = "UK", year = 2000:2004,
                             age_first = 0, age_last = 0,
                             coverage = "seven", doses = NA,
                             targeting = "random")
    expect_equal(nrow(x), 5)
    expect_error(validate_vacc_activities(x)) ## !coverage

    x <- popim_vacc_activities(region = "UK", year = 2000:2004,
                             age_first = 0, age_last = 0,
                             coverage = 0.5, doses = NA, targeting = -1)
    expect_equal(nrow(x), 5)
    expect_error(validate_vacc_activities(x)) ## !targeting
})
test_that("validate_vacc_activities fails when both coverage and doses are missing", {
    x <- popim_vacc_activities(region = "UK", year = 2000:2004,
                             age_first = 0, age_last = 0,
                             coverage = 0, doses = NA, targeting = "random")
    expect_equal(nrow(x), 5)
    expect_no_error(validate_vacc_activities(x))

    x <- popim_vacc_activities(region = "UK", year = 2000:2004,
                             age_first = 0, age_last = 0,
                             coverage = NA, doses = 0, targeting = "random")
    expect_equal(nrow(x), 5)
    expect_no_error(validate_vacc_activities(x))

    x$doses[2] <- NA ## coverage and doses both missing in one row
    expect_error(validate_vacc_activities(x))

    x$coverage[2] <- 1 ## some rows have coverage, some doses
    expect_no_error(validate_vacc_activities(x))
})
