test_that("validate_vacc_activities detects invalid object generated by new_vacc_activities", {
    x <- new_vacc_activities(year = 2000, age_first = -1, age_last = 10,
                             coverage = 0.3, targeting = "random")
    expect_equal(nrow(x), 1)
    expect_error(validate_vacc_activities(x)) ## because age_first

    x <- new_vacc_activities(year = 2000, age_first = 10, age_last = 5,
                             coverage = 0.3, targeting = "random")
    expect_equal(nrow(x), 1)
    expect_error(validate_vacc_activities(x)) ## because age_last < age_first

    x <- new_vacc_activities(year = 2000,
                             age_first = 0, age_last = 5,
                             coverage = 2, targeting = "random")
    expect_equal(nrow(x), 1)
    expect_error(validate_vacc_activities(x)) ## because coverage

    x <- new_vacc_activities(year = 2000,
                             age_first = 0, age_last = 5,
                             coverage = 0.5, targeting = "blue")

    expect_equal(nrow(x), 1)
    expect_error(validate_vacc_activities(x)) ## because targeting
    
    
    
    x <- new_vacc_activities(year = 2000:2004,
                             age_first = 0, age_last = 0,
                             coverage = "seven", targeting = "random")
    expect_equal(nrow(x), 5)
    expect_error(validate_vacc_activities(x)) ## !coverage

    x <- new_vacc_activities(year = 2000:2004,
                             age_first = 0, age_last = 0,
                             coverage = 0.5, targeting = -1)
    expect_equal(nrow(x), 5)
    expect_error(validate_vacc_activities(x)) ## !targeting
})
