##' Function to test if the argument is a valid population dataframe
##'
##' This function tests whether the supplied argument is a valid
##' population dataframe such as might be generated by the function
##' "setup_population".  This currently only tests the structure, not
##' the content of the dataframe.
##' @param x argument to be tested if it fulfils the requirements for
##'     a population dataframe.
##' @return logical
##' @author Tini Garske
##' @export
is_population <- function(x) {

    if(!(class(x) == "data.frame" &
         ncol(x) >= 4 &
         "year" %in% names(x) &
         "age" %in% names(x) &
         "cohort" %in% names(x) &
         "immunity" %in% names(x)))
        return(FALSE)

    if(class(x$year) != "integer" |
       class(x$age) != "integer" |
       class(x$cohort) != "integer" |
       class(x$immunity) != "numeric")
        return(FALSE)

    return(TRUE)
}
