##' Function to test if the argument is a valid population dataframe
##'
##' This function tests whether the supplied argument is a valid
##' population dataframe such as might be generated by the function
##' "vip_population".
##' @param x argument to be tested if it fulfils the requirements for
##'     a population dataframe.
##' @param tol numerical, determines the tolerance when comparing two
##'     numbers. Defaults to the square root of machine precision.
##' @return logical
##' @author Tini Garske
is_population <- function(x, tol = .Machine$double.eps^0.5) {
    ## This could be improved with sensible error messages in the
    ## assert_... style.

    assert_population(x)

    if(!(ncol(x) >= 5 &&
         "region" %in% names(x) &&
         "year" %in% names(x) &&
         "age" %in% names(x) &&
         "cohort" %in% names(x) &&
         "immunity" %in% names(x)))
        return(FALSE)

    if(class(x$region) != "character" ||
       class(x$year) != "integer" ||
       class(x$age) != "integer" ||
       class(x$cohort) != "integer" ||
       class(x$immunity) != "numeric")
        return(FALSE)

    if(!(min(x$age) >= 0 &&
         min(x$immunity, na.rm = TRUE) >= 0 &&
         max(x$immunity, na.rm = TRUE) <= 1))
        return(FALSE)

    if(any(x$year - x$age - x$cohort > tol))
        return(FALSE)

    if("pop_size" %in% names(x)) {
        if(!is.numeric(x$pop_size)) return(FALSE)
        if(sum(!is.na(x$pop_size)) > 0 &&
           min(x$pop_size, na.rm = TRUE) < 0) return(FALSE)
    }

    TRUE
}
